services:
  postgres:
    image: postgres:17-alpine
    container_name: codritium_postgres
    environment:
      POSTGRES_USER: codritium
      POSTGRES_PASSWORD: codritium
      POSTGRES_DB: codritium
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "codritium"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
