package grader

import (
	"strings"
	"testing"
)

func TestSanitizeCode_AuthorPositive(t *testing.T) {
	in := `// @author Alice Wonderland
package foo
func Bar() {}`
	out := SanitizeCode(in)
	if strings.Contains(out, "@author") {
		t.Errorf("expected @author line removed, got: %q", out)
	}
	if !strings.Contains(out, "package foo") {
		t.Errorf("legitimate code line missing: %q", out)
	}
}

func TestSanitizeCode_AuthorFalsePositiveFree(t *testing.T) {
	// "by" alone must NOT delete legitimate lines.
	cases := []string{
		"// sorted by name",
		"// list filtered by criteria",
		"# generated by tool but date stripped separately",
		"by reference passes through unchanged",
	}
	for _, c := range cases {
		out := SanitizeCode(c)
		if out != c {
			t.Errorf("legitimate line was modified:\n  in : %q\n  out: %q", c, out)
		}
	}
}

func TestSanitizeCode_VersionMarker(t *testing.T) {
	in := `// v2 of legacy module
// rewrite of api_v1
real code here`
	out := SanitizeCode(in)
	if strings.Contains(out, "v2 of") || strings.Contains(out, "rewrite of") {
		t.Errorf("version marker not removed: %q", out)
	}
	if !strings.Contains(out, "real code here") {
		t.Errorf("code body missing: %q", out)
	}
}

func TestSanitizeCode_DateMarker(t *testing.T) {
	in := `// Created: 2024-03-15
// Last modified: 2025-01-01
func foo() {}`
	out := SanitizeCode(in)
	if strings.Contains(out, "Created:") || strings.Contains(out, "Last modified:") {
		t.Errorf("date markers not removed: %q", out)
	}
}

func TestSanitizeHistory_BrandReplacement(t *testing.T) {
	items := []PromptHistoryItem{
		{Role: "user", Content: "I asked Claude to refactor this"},
		{Role: "assistant", Content: "ChatGPT also suggests using GPT-4 here"},
		{Role: "user", Content: "Gemini gave me Claude Sonnet style advice"},
	}
	out := SanitizeHistory(items)
	for _, it := range out {
		for _, bad := range []string{"Claude", "ChatGPT", "GPT-4", "Gemini"} {
			if strings.Contains(it.Content, bad) {
				t.Errorf("brand %q not replaced in: %q", bad, it.Content)
			}
		}
	}
}

func TestSanitizeHistory_CursorIsAllowed(t *testing.T) {
	// "cursor" should NOT be replaced — too ambiguous (DB cursor, IDE cursor, pagination).
	items := []PromptHistoryItem{
		{Role: "user", Content: "move the cursor to the next position"},
	}
	out := SanitizeHistory(items)
	if !strings.Contains(out[0].Content, "cursor") {
		t.Errorf("cursor was wrongly replaced: %q", out[0].Content)
	}
}

func TestSanitizeInput_NoCallerMutation(t *testing.T) {
	in := GraderInput{
		CandidateFiles: map[string]string{"a.py": "// @author Alice\nprint(1)"},
		PromptHistory:  []PromptHistoryItem{{Role: "user", Content: "ask Claude"}},
	}
	_ = SanitizeInput(in)
	if !strings.Contains(in.CandidateFiles["a.py"], "@author Alice") {
		t.Errorf("caller's CandidateFiles was mutated")
	}
	if !strings.Contains(in.PromptHistory[0].Content, "Claude") {
		t.Errorf("caller's PromptHistory was mutated")
	}
}
